name: Categorize Repositories

on:
  workflow_dispatch:
  schedule:
    # weekly on Monday at 00:00 UTC
    - cron: '0 0 * * 1'

jobs:
  categorize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Always checkout the branch HEAD to include latest commits (e.g., on reruns)
          ref: ${{ github.ref }}
          # Fetch full history for accurate push/rebase operations
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests openai
      - name: Mask OpenAI API key in logs
        run: echo "::add-mask::${{ secrets.OPENAI_API_KEY }}"
      - name: Generate repository categories
        run: python scripts/generate_repo_categories.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update REPO_CATEGORIES.md"
          branch: ${{ github.ref_name }}
          file_pattern: REPO_CATEGORIES.md
          # Force push to overwrite any divergent commits (e.g., on reruns)
          push_options: '--force-with-lease'